fluentd:
  build: ./fluentd
  ports:
    - 24224:24224/tcp
    - 24224:24224/udp

elasticsearch:
  image: elasticsearch:latest
  ports:
    - 9200:9200
    - 9300:9300

kibana:
  image: kibana:latest
  environment:
    - ELASTICSEARCH_URL=http://172.17.0.4:9200
  ports:
    - 5601:5601